name: Release

on:
  workflow_dispatch:

jobs:
  lock-branch:
    if: github.ref_name == 'master' || startsWith(github.ref_name, 'version/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lock base branch
        env:
          BRANCH: ${{ github.ref_name }}
          LOCK: 'true'
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./scripts/ci/steps/set-branch-lock.sh

  build:
    needs: lock-branch
    uses: ./.github/workflows/build.yml
    with:
      cypress-test-all-browsers: true
    secrets: inherit

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Simulate release (1 min wait)
        run: sleep 60
      - name: Unlock base branch
        env:
          BRANCH: ${{ github.ref_name }}
          LOCK: 'false'
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./scripts/ci/steps/set-branch-lock.sh
