name: Release Cleanup

on:
  workflow_run:
    workflows: ['Release']
    types:
      - completed

jobs:
  unlock-branch:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.head_branch == 'master' || startsWith(github.event.workflow_run.head_branch, 'version/')
    steps:
      - uses: actions/checkout@v4
      - name: Ensure base branch is unlocked (failsafe)
        env:
          BRANCH: ${{ github.event.workflow_run.head_branch }}
          LOCK: 'false'
          GH_TOKEN: ${{ secrets.TEST_WORKFLOW_ADMIN_TOKEN_3 }}
        run: ./scripts/ci/steps/set-branch-lock.sh
